### ISSUE TITLE
TypeError not performing as intended

### ISSUE THREAD

**Issue by s-flint-defra** [Defra-Data-Science-Centre-of-Excellence/sds-data-model#14] opened 2022-06-16 07:39 UTC
I am getting an error "TypeError: CRS must be OSGB36 / British National Grid, not OSGB 1936 / British National Grid" - is this intended behaviour?

When using _VectorLayer.from_files_

**Comment by danlewis85** [comment] 2022-06-16 08:22
This error arises because the `BNG` string in `constants.py` is set as: "OSGB36 / British National Grid", whereas the crs name for epsg:27700 seems to return "OSGB 1936 / British National Grid". The check is only a string equivalence so it fails.

A quick work around is to simply update the string in `constants.py` to "OSGB 1936 / British National Grid" so that the check will pass.

A formal fix may require us to dig into whether there are specific approaches for comparing crs.

**Comment by s-flint-defra** [comment] 2022-06-16 09:36
Thanks Dan, I've already amended the constants file - flagging the issue as presumably Ed encountered the alternative string during development and i'm unsure how common this could be. 

Using print(geodataframe.crs) produces the epsg version: 'epsg:27700' - I wonder if this would be more consistent between files.

**Comment by danlewis85** [comment] 2022-06-16 09:44
From what I recall, the differences might arise due to how a crs is referenced in provided data, versus how it is referenced in the proj string associated with given epsg codes. It might be overkill, but an approach could be to look at the `osgeo.osr.SpatialReference` `is_same()` method: https://gdal.org/python/osgeo.osr.SpatialReference-class.html

**Comment by TimAshelford** [comment] 2022-07-20 09:20
duplicate of #40

**Closed as completed by TimAshelford** 2022-07-20 09:20 UTC
