### ISSUE TITLE
`to_dataset_as_raster` not accepting string columns

### ISSUE THREAD

**Issue by jpd-defra** [Defra-Data-Science-Centre-of-Excellence/sds-data-model#28] opened 2022-07-01 12:37 UTC
The `to_dataset_as_raster` function relies on `rasterio.dtypes.get_minimum_dtype` to work out minimum data type. However this function does not account for columns with strings and throws an error if provided with one.

@s-flint-defra suggests following datacube's approach of handling other datatypes.

**Comment by TimAshelford** [comment] 2022-07-20 09:20
duplicate of  #33

**Closed as completed by TimAshelford** 2022-07-20 09:20 UTC
